on:
  push:
    branches:
    - main
  pull_request:

name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.18.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Setup dependency - gcc
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo apt update -y
        sudo apt-get install build-essential -y
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - run: go test ./...